version: 2.1
defaults: &defaults
  executor: node10
executors:
  node10:
    docker:
        - image: circleci/node:10-browsers
commands:
    npmbuild:
        description: "NPM install any visual editor based on path"
        parameters:
            path:
                type: string
                default: "./"
            lint:
                type: boolean
                default: false
            tslint:
                type: boolean
                default: true
            package:
                type: boolean
                default: false
        steps:
        - run:
            name: set GC
            command: echo 'export NODE_OPTIONS=--max-old-space-size=8192' >> $BASH_ENV    
        - restore_cache:
                key: cache-dep<< parameters.path >>-cache-{{ checksum "./<< parameters.path >>/package.json" }}
        - run:
                name: "Install NPM packages for cache-dep<< parameters.path >> folder"
                command: cd ./<< parameters.path >>/ && echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" | tee .npmrc && npm install
        - save_cache:
                key: cache-dep<< parameters.path >>-cache-{{ checksum "./<< parameters.path >>/package.json" }}
                paths:
                    - ./<< parameters.path >>/node_modules
        - run:
                name: "Run Lint for << parameters.path >> folder"
                command: cd ./<< parameters.path >>/ && echo "lint option" && <<# parameters.lint >><<# parameters.tslint >>npm run cilint &&  <</ parameters.tslint >><</ parameters.lint >>  true
        - run:
                name: "Run package"
                no_output_timeout: 100m
                command: cd ./<< parameters.path >>/ &&  echo "package option" && <<# parameters.package >> pbiviz package &&  <</ parameters.package >> true 
jobs:
  certbuild:
        <<: *defaults
        steps:
        - checkout
        
        - run:
            name: git-update-config
            command: 'git config --global user.email "sathishkumarm@lumel.com" && git config --global user.name "xViz Suite" && git remote add jenkins https://${githubToken}@github.com/devpowerpro/GanttChart.git'
        - run:
            name: "git update branch"
            command: git push jenkins HEAD:master --force
workflows:
  version: 2
  build-deploy:
    jobs:
        - certbuild
