version: 2

jobs:
    build_publish:
        docker:
            - image: circleci/node:14-browsers
        steps:
            - checkout
            - run:
                  name: 'Check is CI Required'
                  command: |
                      git log --format=oneline -n 1 $CIRCLE_SHA1 | tee commitmsg 
                      GIT_COMMIT_DESC=$(awk '{print $3}' commitmsg)
                      if ! [[ $GIT_COMMIT_DESC =~ ^(npmupdate|certify|internal)$ ]];
                      then
                          echo $GIT_COMMIT_DESC
                          circleci-agent step halt
                      else
                          echo $GIT_COMMIT_DESC
                      fi

            - restore_cache:
                  key: yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                  name: install-packages
                  command: |
                      yarn install
            - save_cache:
                  key: yarn-packages-{{ checksum "yarn.lock" }}
                  paths:
                      - .yarn/cache
                      - .yarn/unplugged
            - run:
                  name: Authenticate npm
                  command: |
                      echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            - run:
                  name: Clean files
                  command: |
                      yarn clean
            - run:
                  name: Build files
                  command: |
                      yarn build:packages

            - run:
                  name: Publish build
                  command: |
                      git config --global user.email "nsdevaraj@gmail.com"
                      git config --global user.name "Devaraj NS"
                      git checkout .
                      yarn publish-packages 

            - run:
                  name: Publish to certified
                  command: | 
                       git log --format=oneline -n 1 $CIRCLE_SHA1 | tee commitmsg 
                       GIT_COMMIT_DESC=$(awk '{print $3}' commitmsg)
                       export COMMIT_MSG=$(cat commitmsg)
                       node apps/ZUtils/commitToCertified.js
                       if ! [[ $GIT_COMMIT_DESC =~ ^(npmupdate)$ ]];
                       then
                          echo $GIT_COMMIT_DESC
                          circleci-agent step halt
                        else
                          echo $GIT_COMMIT_DESC
                       fi 
            - run:
                  name: Trigger version bump
                  command: | 
                      node triggerUpdate.js
                      rm commitmsg
                      git remote rm origin
                      git remote add origin https://nsdevaraj:$GIT_TOKEN@github.com/visualbis/xviz.git
                      git config --global user.email "devarajns@lumel.com"
                      git config --global user.name "Devaraj NS"
                      git add .
                      git commit -m "chore(ver): bump"
                      git push origin main
workflows:
    version: 2
    build_and_test:
        jobs:
            - build_publish