version: 2

jobs:
    build_publish:
        docker:
            - image: circleci/node:14-browsers
        steps:
            - checkout
            - run:
                   name: 'Avoid CI build'
                   command: |
                      echo $CIRCLE_SHA1
                      echo $CIRCLE_PROJECT_USERNAME
                      git log --format=oneline -n 1 $CIRCLE_SHA1 | tee commitmsg
                      if grep -q 'builds' commitmsg; then
                          echo "publish" 
                      else
                          circleci-agent step halt
                      fi
            - restore_cache:
                  key: yarn-packages-{{ checksum "yarn.lock" }}
            - run:
                  name: install-packages
                  command: |
                      yarn install
            - save_cache:
                  key: yarn-packages-{{ checksum "yarn.lock" }}
                  paths:
                      - .yarn/cache
                      - .yarn/unplugged
            - run:
                  name: Authenticate npm
                  command: |
                      echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            - run:
                  name: Clean files
                  command: |
                      yarn clean
            - run:
                  name: Build files
                  command: |
                      yarn build:packages

            - run:
                  name: Publish build
                  command: |
                      git config --global user.email "nsdevaraj@gmail.com"
                      git config --global user.name "Devaraj NS"
                      git checkout .
                      yarn publish-packages 

            - run:
                  name: Publish to certified
                  command: | 
                       git log --format=oneline -n 1 $CIRCLE_SHA1 | tee commitmsg 
                       GIT_COMMIT_DESC=$(awk '{print $3}' commitmsg)
                       export COMMIT_MSG=$(cat commitmsg)
                       node ./ZUtils/commitToCertified.js
                       if ! [[ $GIT_COMMIT_DESC =~ ^(npmupdate)$ ]];
                       then
                          echo $GIT_COMMIT_DESC
                          circleci-agent step halt
                        else
                          echo $GIT_COMMIT_DESC
                       fi 
           
workflows:
    version: 2
    build_and_test:
        jobs:
            - build_publish